### ISSUE TITLE
Add an origin function.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/http#22]
This might be a bit beyond the scope of this library but I always end up creating the following function. The purpose is to find the origin of a request, falling back to the referer header if origin is not present.

> browsers may not send the Origin header, as in the following cases:
>
>    img tags will not send Origin headers unless the crossorigin attribute is set>
>    Chrome and Safari will not send Origin headers with same-origin GET requests
>    Firefox will not send the Origin header with any same-origin requests (bug)
>    Firefox will not send the Origin header with cross-origin form POSTs (bug)
>
> However, in all of these cases, the browser does send a Referer header. We can make use of the Referer header, which browser-initiated requests may not spoof, in place of the missing Origin header

I would call it `http.get_req_origin`

**Comment by cschembor3** [comment]
I think we can close this now, right?

**Comment by lpil** [comment]
Thank you
