### ISSUE TITLE
Conflicting `None` definitions

### ISSUE THREAD

**Issue by sporto** [gleam-lang/http#29]
The `http` module imports `None` from `option`.
And also defines `SameSitePolicy.None`.
When trying to run the tests I get:

```
error: Type mismatch
    ââ /home/sebastian/Source/sporto/http/src/gleam/http.gleam:151:15
    â
151 â     userinfo: None,
    â               ^^^^

Expected type:

    Option(String)

Found type:

    SameSitePolicy
```

**Comment by sporto** [comment]
In https://github.com/gleam-lang/http/pull/28 I added `option.None` which fixes this.

**Comment by lpil** [comment]
Thank you!
