### ISSUE TITLE
`path_segments` should not include query or fragment with the final segment

### ISSUE THREAD

**Issue by lpil** [gleam-lang/http#39]
```
/one/two?three=four#five
```

Should return
```ocaml
["one", "two"]
```

**Comment by mrkutly** [comment]
@lpil I would love to take a crack at this one! I am wondering if this should be fixed in the `gleam/http/request` module or in the stdlib's `gleam/uri` module?

**Comment by lpil** [comment]
Hey @mrkutly ! Thanks for your help. I think we should avoid having the query in the path at all

**Comment by mrkutly** [comment]
Sounds good! @lpil Do you have steps to reproduce the case where you were seeing query strings show up in the `Request path`?

**Comment by lpil** [comment]
I thin this may have been a bug in the `gleam_elli` library which was since fixed.

Looks like we are confident everything works here now so we can close this ticket. Thank you for your investigation 💜
